### ISSUE TITLE
front-end venue stuff

### ISSUE THREAD

**Issue by hcmgr** [Wo-m/tickexperience-frontend#14]
-retreiving and displaying venue location from google geo coding API
-retreiving and displaying venue map

**Comment by Wo-m** [comment]
can you make this a component that can be easily injected into the my tickets and/or events pages. I'm thinking for instance in the ticket details page will have this injected into it, and pass the venue ID to the component to show the venue info. So from the "venue-components" pov it just needs the venueId, and makes a REST call to backend to get info.

For passing info to components look at the @Input annotation:

parent html:
```
<app-venue-component [data] = data ><app-venue-component/> 
```
app-venue-component.ts:
```
@Input
data: {someType};
```

can read more here: https://angular.io/guide/component-interaction

**Comment by hcmgr** [comment]
ye aight I'll work on that next

**Comment by hcmgr** [comment]
grumba meister

**Comment by hcmgr** [comment]
is a pretty good name i think

**Comment by hcmgr** [comment]
wait no

**Comment by hcmgr** [comment]
wait yes
