### ISSUE TITLE
Dummy Data

### ISSUE THREAD

**Issue by Wo-m** [Wo-m/tickexperience-frontend#17]
Create sql script to load a bunch of dummy tickets. Will need venues and events as well

**Comment by glspanevello** [comment]
@Wo-m I've done the dummy data for sports, venues and events. Would you like me to write the sql script to load them in as well?

**Comment by Wo-m** [comment]
Yeh go for it, just keep in mind you will have to add some fields to tables. 

Just create a new sql script and add it to the changelog, look at how h2_setup.sql is done. Give me a shout if you need a hand

**Comment by Wo-m** [comment]
probably a bit late, but you can access the db console with localhost:8080/h2-console (when the backend is running) where you can run sql directly against the DB

may help with testing sql scripts
